### ISSUE TITLE
food_delivery_app\android\gradlew.bat" exited abnormally

### ISSUE THREAD

**Issue by isofttechn** [jaasaria/flutter.FH2019#1]
I have followed all the steps for installation.
On launching, I got the error:
Error running Gradle:
ProcessException: Process "food_delivery_app\android\gradlew.bat" exited abnormally:

  Command: food_delivery_app\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.

Is there like APIs or firebase suffs I need to add before running?

**Comment by jaasaria** [comment]
add this under "projfolder/android/local.properties" , below flutter.sdk key

```
flutter.buildMode=debug
flutter.versionName=1.0.2
flutter.versionCode=2
```
pubspec.yaml and local.properties version must with same value
